server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: online-examination-system
  
  datasource:
    url: jdbc:mysql://localhost:3306/online_exam_system?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        
  security:
    user:
      name: admin
      password: admin

# JWT Configuration
jwt:
  secret: mySecretKey
  expiration: 86400000 # 24 hours in milliseconds

# Swagger Configuration
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method

# Logging
logging:
  level:
    com.onlineexam: DEBUG
    org.springframework.security: DEBUG

